// Lista de permisos en español
export const PERMISOS = [
  'menu_principal',
  'seguridad',
  'seguridad_usuarios',
  'seguridad_roles',
  'seguridad_permisos',
  'seguridad_parroquias',
  'seguridad_parroquias_ver',
  'seguridad_parroquias_crear',
  'seguridad_parroquias_editar',
  'seguridad_parroquias_eliminar',
  'seguridad_roles_ver',
  'seguridad_roles_crear',
  'seguridad_roles_editar',
  'seguridad_roles_eliminar',
  'seguridad_roles_cambiar_estado',
  'seguridad_usuarios_ver',
  'seguridad_usuarios_crear',
  'seguridad_usuarios_editar',
  'seguridad_usuarios_eliminar',
  'seguridad_usuarios_cambiar_estado',
  'personal',
  'liturgico',
  'liturgico_actos',
  'liturgico_actos_ver',
  'liturgico_actos_crear',
  'liturgico_actos_editar',
  'liturgico_actos_eliminar',
  'liturgico_horarios',
  'liturgico_reservas',
  'liturgico_reservas_ver',
  'liturgico_reservas_crear',
  'liturgico_reservas_editar',
  'liturgico_reservas_eliminar',
  'liturgico_reportes',
  'reportes_gerenciales',
  'reportes_transaccionales',
  'contabilidad',
  'ventas',
  'compras',
  'almacen',
  'configuracion',
  'reportes',
];

// Etiquetas legibles para UI
export const ETIQUETAS_PERMISOS = {
  menu_principal: 'Menú Principal',
  seguridad: 'Seguridad',
  seguridad_usuarios: 'Seguridad - usuarios',
  seguridad_roles: 'Seguridad - roles',
  seguridad_permisos: 'Seguridad - permisos',
  seguridad_parroquias: 'Seguridad - parroquias',
  seguridad_parroquias_ver: 'Parroquias - ver',
  seguridad_parroquias_crear: 'Parroquias - crear',
  seguridad_parroquias_editar: 'Parroquias - editar',
  seguridad_parroquias_eliminar: 'Parroquias - eliminar',
  seguridad_roles_ver: 'Roles - ver',
  seguridad_roles_crear: 'Roles - crear',
  seguridad_roles_editar: 'Roles - editar',
  seguridad_roles_eliminar: 'Roles - eliminar',
  seguridad_roles_cambiar_estado: 'Roles - cambiar estado',
  seguridad_usuarios_ver: 'Usuarios - ver',
  seguridad_usuarios_crear: 'Usuarios - crear',
  seguridad_usuarios_editar: 'Usuarios - editar',
  seguridad_usuarios_eliminar: 'Usuarios - eliminar',
  seguridad_usuarios_cambiar_estado: 'Usuarios - cambiar estado',
  personal: 'Personal',
  liturgico: 'Litúrgico',
  liturgico_actos: 'Actos Litúrgicos - gestión',
  liturgico_actos_ver: 'Actos Litúrgicos - ver detalle',
  liturgico_actos_crear: 'Actos Litúrgicos - crear',
  liturgico_actos_editar: 'Actos Litúrgicos - editar',
  liturgico_actos_eliminar: 'Actos Litúrgicos - eliminar',
  liturgico_horarios: 'Actos Litúrgicos - horarios',
  liturgico_reservas: 'Actos Litúrgicos - reservas',
  liturgico_reportes: 'Actos Litúrgicos - reportes',
  reportes_gerenciales: 'Reportes gerenciales',
  reportes_transaccionales: 'Reportes transaccionales',
  contabilidad: 'Contabilidad',
  ventas: 'Ventas',
  compras: 'Compras',
  almacen: 'Almacén',
  configuracion: 'Configuración',
  reportes: 'Reportes',
};
