"""Add last_activity to User and jti to RefreshToken

Revision ID: 077a65cc0275
Revises: 3bf1a8de9221
Create Date: 2025-10-07 01:02:14.346939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077a65cc0275'
down_revision = '3bf1a8de9221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jti', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(None, ['jti'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activity', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_activity')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('jti')

    # ### end Alembic commands ###
